### PR TITLE
expose ArrayView(Mut)::from_ptr, useful for FFI

### PR DESCRIPTION
**Pull request by vbarrielle**
See #209 for the intent: fast-path for interfacing with FFI-allocated arrays.

### CODE REVIEW

**Comment by bluss** [comment]
Thank you.

Looking with consistency eyes, here are some thoughts:

`std::slice::from_raw_parts` suggests that maybe it can be named from_raw_parts.

The other array constructors now use a size/shape object as one parameter for convenience, we should use that. Example link: https://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.from_shape_vec

Going all the way would be to have both `from_shape_ptr(shape, ptr) -> Result<ArrayView<..>>` and `from_shape_ptr_unchecked(shape, ptr) -> ArrayView<..>` and this would undeniably be consistent, and promote a checked version as the preferred approach.

However there is only so much checking that we can do. We have to trust the caller that the pointer is valid for the whole needed range. Maybe the checked version won't see any use anyway.

`from_shape_ptr(shape, ptr) -> ArrayView<..>` would be fine for that reason, and it's simple to call if you just use default strides, or you can just use for example `ArrayView::from_shape_ptr((m, n).f(), ptr)` to have f-order.

**Comment by vbarrielle** [comment]
As far as I can tell, the only check that can be performed would be verifying that the strides do not allow indexing the same element with different indices. So I'd say having only ``from_shape_ptr(shape, ptr) -> ArrayView<..>`` should be enough.

**Comment by bluss** [comment]
yes

**Comment by vbarrielle** [comment]
Here's a new version with the rename, and the unchecked ``from_shape_ptr`` version.

**Comment by fkjogu** [comment]
Doing a quick test, I can confirm this works quiet nicely. Thank you so much.

**Comment by bluss** [comment]
Thank you! Merging and will do changes on top of that. The from_raw_parts variants are more or less redundant and will be removed.

**Pull request merged**
