### PR TITLE
Upgrade to serde 1.0

### LINKED ISSUE #314: Update to Serde 1.0
Release notes: https://github.com/serde-rs/serde/releases/tag/v1.0.0

### PR DESCRIPTION
**Pull request by Libbum**
Fixes #314.

Wasn't anything too major to do and all tests pass. I'm using it at the moment on one of my projects and everything seems good, but I'm still a little green when it comes to rust; so someone with a bit more experience may want to do a review.

### CODE REVIEW

**Comment by bluss** [comment]
I pushed the WIP I had sitting ( https://github.com/bluss/rust-ndarray/tree/serde-1 ) so I guess, sorry for the doubled work, fortunately it's a simple thing.

**Comment by Libbum** [comment]
No worries. I needed it quickly and could see you've been busy, so thought I may give it a shot. Good to see my implementation is effectively the same as yours - looks like I'm learning the right way to do things!

**Comment by bluss** [comment]
This will need a major version bump to 0.10, so I guess that has been slowing it down. A few things here and there need to be updated.

**Comment by Libbum** [comment]
Fair enough - not a problem. If you've got the plan sorted out then there's no need for this PR, so you're welcome to close it. I'll try to help out in some other places soon.

**Comment by bluss** [comment]
Thanks, now has a successor.

**Pull request closed without merging**
