### PR TITLE
BUG: Fix blas + axpy by only using it for certain cases

### PR DESCRIPTION
**Pull request by bluss**
Only use blas axpy for 1D arrays or contiguous arrays.

### CODE REVIEW

**Comment by bluss** [comment]
cc @SuperFluffy

**Comment by SuperFluffy** [comment]
Other than the negative and zero stride case, did you find anything that would prevent using blas for non-contiguous but equispaced/compatible arrays?

**Comment by bluss** [comment]
It should be fine. Equispaced stride doesn't cover one case though, which is F1 + F2 (both arrays are 2+ dimensions, same shape, but in fortran memory order).

**Comment by bluss** [comment]
Changed to a revert since it broke existing uses of is_contiguous (for negative stride arrays). It's my responsibility to decide on merges, so it's my responsibility there is a bug.

**Comment by bluss** [comment]
A clearer thought on the situation is that we have two input arrays, and we need to figure out if they are separately blas compatible, but also that they are memory order compatible with each other. Same problem that zip needs to solve.

**Pull request merged**
