### PR TITLE
Update ndarray-rand random function, format with rustfmt

### PR DESCRIPTION
**Pull request by v-shmyhlo**
Hello community, my very first contribution to open source, please feel free to criticize what i am doing so i could learn and become better contributor.
* formatted code with rustfmt
* random function updated to use `from_shape_fn` constructor, which i think is more suitable (please correct me if i am wrong)
* added explicit types to benches to better show the intent of using `F32`

### CODE REVIEW

**Comment by bluss** [comment]
Hi, thanks for your interest in ndarray!

Please hold off formatting for now -- the whole project wants to move to that relatively orderly, including using a rustfmt formatting configuration file in the repo. Also keep in mind to not mix feature commits with formatting commits. With that said, the feature change (using from_shape_fn) looks good to me, and it's good to submit that one alone. It might even be a performance improvement this way.

**Comment by v-shmyhlo** [comment]
@bluss, I have updated PR according to your comment, thank you very much for descriptive answer!

**Comment by bluss** [comment]
Thanks!

**Comment by bluss** [comment]
This is now in ndarray-rand 0.6.1. Just thought I'd notice you. Normally we make very little fuss about releases though, just make new ones all the time.

**Pull request merged**
