### PR TITLE
Enable indexing Dimension by Axis

### LINKED ISSUE #111: Implementing Index<Axis> for Dimension
This would allow using `a.dim()[Axis(0)]`, which is not that much of a win. However, when implementing a method that takes an Axis as an argument, this could be a real win:
`a.dim().slice()[axis.axis()]` vs `a.dim()[axis]`.

What do you think?

### PR DESCRIPTION
**Pull request by vbarrielle**
Fixes #111 

Due to coherence rules I've had to use a macro. Looks like it works fine.

### CODE REVIEW

**Comment by bluss** [comment]
It seems this is not enough for it to be useful with just `D: Dimension`? Maybe there is another way, so that we don't have to make this interface public. My idea is that it should not be a part of ndarrays external API.

**Comment by vbarrielle** [comment]
Yes avoiding to expose this too much would be nice, but I don't know if it's possible. Right now I have no idea how to restrict this.

**Comment by bluss** [comment]
We can add a new method to `Dimension` (or two).

**Comment by vbarrielle** [comment]
Right, simply being able to use `a.dim().index(axis)` would be nice.

**Comment by vbarrielle** [comment]
The methods are added to the trait now. I haven't added doc for them yet, but I will.

**Comment by bluss** [comment]
Looks good. This gives me food for thought regarding the issue of hiding these implementation details. `Dimension` is good because we can use it to specialize each method while also providing a general implementation. But that's a larger question outside of this PR.

**Comment by vbarrielle** [comment]
I added some documentation on these new members.

**Comment by bluss** [comment]
Thank you!

**Comment by vbarrielle** [comment]
You're welcome.

**Pull request merged**
