### PR TITLE
Rename raw_dimension → raw_dim, better docs, expand prelude

### PR DESCRIPTION
**Pull request by bluss**
- The prelude gains all the dimensionality-specific type aliases.

### CODE REVIEW

**Comment by bluss** [comment]
cc @SuperFluffy do you want to review this? The prelude becomes very large.

**Comment by SuperFluffy** [comment]
Would you like a review on the entire PR or only prelude?

I like the prelude. One can always choose to not import it. But it looks like it contains everything that I tend to use with `ndarray`. I might actually switch over to prelude. :D

**Comment by bluss** [comment]
mainly the prelude changes. Yeah it's optional to use it, and it's hard to pick a smaller subset. It could for example only include dimensionalities 0, 1, 2, but that doesn't reduce the logical complexity of the prelude at all, only the number of items.

**Comment by SuperFluffy** [comment]
Yes, that was my thought, too. Furthermore, it would be inconsistent. Why would import a certain subset of indices or dimensionalities, but not all of them? I think that would be quite confusing and not very useful.

I think either import all of the sets, or none of them.

**Pull request merged**
