### PR TITLE
Add ArrayBase.insert_axis() and Dimension::Larger

### PR DESCRIPTION
**Pull request by jturner314**
This adds a method to ArrayBase to insert a new (length 1) axis. See #352 for the reasoning behind this feature. I modeled the implementation on the `.remove_axis()` method.

I originally tried implementing `.insert_axis()` using `Dimension::Smaller` for the input type (as suggested by @bluss). The signature was
```rust
impl<A, S, D> ArrayBase<S, D> where S: Data<Elem=A>, D: Dimension {
    pub fn insert_axis<D2: Dimension<Smaller=D>>(self, axis: Axis) -> ArrayBase<S, D2> where D2: InsertAxis {...}
}
```
The disadvantage of that approach was that the caller of `.insert_axis()` had to disambiguate the return type, since multiple types could implement `Dimension<Smaller=D>`. For example,
```rust
let a = arr1(&[1, 2, 3]);
let col = a.insert_axis(Axis(1)); // didn't compile; had to specify return type Array2<_>
println!("{:?}", col);
```
As a result, the cleanest method was to add the `Dimension::Larger` associated type, which makes the above example work without specifying the return type. The signature is then
```rust
impl<A, S, D> ArrayBase<S, D> where S: Data<Elem=A>, D: Dimension {
    pub fn insert_axis(self, axis: Axis) -> ArrayBase<S, D::Larger> where D: InsertAxis {...}
}
```

Please let me know what you think.

### CODE REVIEW

**Comment by bluss** [comment]
Looks good. I'd shoot for not having any new trait in the public API here, and I'll try to resolve that too if I have time. feel free to ping me about this later.

**Comment by jturner314** [comment]
That's a good point about avoiding adding an `InsertAxis` trait. I just pushed a new version. I expect that it's slightly less efficient since it creates a `Vec` for all cases, not just when `D::Larger` is `IxDyn`, but it's simpler and doesn't add a new trait to the public API.

**Comment by jturner314** [comment]
I think if you wanted to keep the more efficient implementation, you could make `InsertAxis` private and provide an implementation for all types that implement `Dimension` (using the body of the `dim_insert_axis` function in dbe871edea073823f53ccd8dc0e3a90519dc0a53). Then, `insert_axis` for `Ix0`, `Ix1`, ... `Ix5` could still be separately implemented (as in 0edc15310ecce8c4f4950f45c7ca48c7cfb0add6). The disadvantage is that this would require more code than dbe871edea073823f53ccd8dc0e3a90519dc0a53.

**Comment by bluss** [comment]
Sorry to send you on the goose chase here. I'd add a new method to the Dimension trait. That trait is locked down so that we can add stuff to it as we want. You can have a default impl and some specific items. In the end we want this to be so good so that we only go into using a Vec if we are in the non-short case for IxDynIml. It uses a short vector optimization nowadays.

**Comment by jturner314** [comment]
Okay, I pushed a new version that adds `.insert_axis()` to the `Dimension` trait and provides specific implementations for the various dimension types. What do you think?

**Comment by bluss** [comment]
Thanks a lot for this

**Pull request merged**
