### PR TITLE
Add documentation for slicing with negative step

### PR DESCRIPTION
**Pull request by jturner314**
See also #312.

### CODE REVIEW

**Comment by bluss** [comment]
Thanks!

**Comment by bluss** [comment]
@jturner314 Do you want to be a co-maintainter of this crate?

**Comment by jturner314** [comment]
@bluss What exactly do you have in mind? I'm happy to help answer issues and review PRs. Would I have write access? I'm comfortable with improving documentation and making bug fixes, but I'm a little hesitant to make/merge public API changes without having someone else take a second look (at least before a new version is released).

**Comment by bluss** [comment]
Sure, write access and coownership of the ndarray crates.

**Comment by jturner314** [comment]
Okay, I accept.

Thanks again for creating `ndarray`! I've recently finished a >10 kloc project that uses `ndarray` extensively, and `ndarray` has worked really well.

**Comment by bluss** [comment]
:star2: Yay! That means we have doubled the number of maintainers of ndarray, thanks to @jturner314  :smile:

**Pull request merged**
