### PR TITLE
Impl `From<ArrayN>` for ArrayD, for N in 0..6

### PR DESCRIPTION
**Pull request by bobogei81123**
* Implement the From<ArrayN> trait for ArrayD to allow conversion
  into dynamic dimensional array.
* Add some tests.

### CODE REVIEW

**Comment by bluss** [comment]
I'd prefer to simply have a method for this. We can implement it once for ArrayBase, so that all array kinds (including views) support this conversion.

**Comment by bobogei81123** [comment]
Ok, but since `ArrayBase<S, D>` only required `D: Dimension`, this means that we have to be able
to cast any `Dimension` into `IxDyn`.

**Comment by bluss** [comment]
Converting any dimension to IxDyn is good. Thanks for the PR — it's a design I agree a lot with. I'll merge and might do adjustments on top of it.

As an aside, individual methods can require what they need. See for example [`.select()`](https://docs.rs/ndarray/0.10.0/ndarray/struct.ArrayBase.html#method.select) which has a where clause, adding extra requirements.

**Comment by bluss** [comment]
Remaining travis failure is the upstream bug ICE that affects matrixmultiply. It has been fixed in Rust, just needs a new nightly.

**Comment by bluss** [comment]
Now in version 0.10.1

**Pull request merged**
