### PR TITLE
Update blas-sys and openblas-provider

### PR DESCRIPTION
**Pull request by IvanUkhov**
I have updated `openblas-provider` to compile OpenBLAS v0.2.17, which was released five days ago.

### CODE REVIEW

**Comment by bluss** [comment]
Thank you!

**Comment by bluss** [comment]
I've been looking at BLIS since it in theory fits ndarray better with its support for arbitrary strides. However, integrating them with rust is not so easy, like most scientific projects it requires a lot of manual work to configure.

**Comment by daniel-vainsencher** [comment]
Just my vote as a particular user: for me an assert preventing stride
mismatch on calls to another blas is just as good.

OTOH, the primitives I use are mostly simple matrix vector products, so I
don't care about using the one "best" BLAS library (scare quotes because
its a multi criteria problem). Encountering configuration problems would be
cost me more than any potential benefit.

On Fri, Mar 25, 2016 at 10:30 AM, bluss <notifications@github.com> wrote:

> I've been looking at BLIS since it in theory fits ndarray better with its
> support for arbitrary strides. However, integrating them with rust is not
> so easy, like most scientific projects it requires a lot of manual work to
> configure.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bluss/rust-ndarray/pull/172#issuecomment-201312250>
>



-- 
Daniel Vainsencher

**Comment by bluss** [comment]
.mat_mul() never fails to compute as long as the matrix dimensions match as the should, it just falls back to the generic matrix multiplication implementation. If the matrix is large enough, the performance difference is huge (more than 10 times slower for a 128x128 matrix multiplication).

But I have said I will not reimplement linear algebra in rust. So for ndarray to support more linear algebra I would prefer to use an external library.

**Comment by IvanUkhov** [comment]
@bluss, where can one read your argumentation agains reimplementing linear algebra in Rust?

**Comment by bluss** [comment]
ndarray wants to provide good solutions, why not use the decades long expertise in linear algebra that others have put into for example BLAS/LAPACK?

**Comment by IvanUkhov** [comment]
Why implementing Servo if we have Gecko?

**Comment by bluss** [comment]
@IvanUkhov ?? I've said I will not implement linear algebra. That's my decision. You can write Servo or linear algebra in rust if you want to.

**Comment by IvanUkhov** [comment]
Sorry, no offense was intended. I just thought that you meant that, in general, it was not worth it rewriting linear algebra in Rust (like it would be drastically slower or something like that).

**Comment by daniel-vainsencher** [comment]
A bit off topic, but I think that linear algebra and web browsers have
completely different tradeoffs. In the first complexity is all about
optimizations, the interfaces are small and very well known. In particular
the ratio potential for unsafety bugs / code size is probably much much
lower than in web browsers that need to e.g. parse and run arbitrary html
etc.

On Fri, Mar 25, 2016 at 12:23 PM, bluss <notifications@github.com> wrote:

> @IvanUkhov <https://github.com/IvanUkhov> ?? I've said I will not
> implement linear algebra. That's my decision. You can write Servo or linear
> algebra in rust if you want to.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bluss/rust-ndarray/pull/172#issuecomment-201349444>
>



-- 
Daniel Vainsencher

**Comment by bluss** [comment]
Aha. The more I looked into BLIS the more I thought they could benefit from Rust. They don't use generics (instead void *), and use C macros a lot. Quite the mess! I think rust can do it just as well, but it will be a lot of raw pointers, unsafe code and asm kernels. Maybe an open question is, how easy is it to use asm from Rust?

**Comment by bluss** [comment]
@daniel-vainsencher Do you use blas + ndarray at the moment? If you don't enjoy hassle with dependencies, I suspect you don't do that. It's an optional ("and experimental") crate feature and I haven't documented it properly yet (it requires picking a BLAS provider deliberately.)

**Comment by daniel-vainsencher** [comment]
I'm not; for matrix.dot(vec) don't see a need to. If your point is that a
more "hassle-y" blas would cause me the exact same amount of hassle (zero,
because not using the feature) you are right at least for now :)

**Comment by bluss** [comment]
@IvanUkhov I apparently had too much time this weekend: http://bluss.github.io/rust/2016/03/28/a-gemmed-rabbit-hole/  (it's an implementation of dgemm in Rust).

**Pull request merged**
