### PR TITLE
Update to serde 0.9

### LINKED ISSUE #270: Update to serde 0.9
https://github.com/serde-rs/serde/releases/tag/v0.9.0

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #270.

### CODE REVIEW

**Comment by bluss** [comment]
Thank you!

@SuperFluffy this should be good to go as it is right?

**Comment by SuperFluffy** [comment]
Yes, I think so! :-)

**Comment by bluss** [comment]
Finally released in ndarray 0.8.0. I was a bit wary of the bump, but it should be ok. It's how it is. We have serde and num as public dependencies and when they bump, we bump. (We're in triple pace that way). Thanks to serde we are dropping rustc-serialize soon enough, so it is not a factor.

**Comment by dtolnay** [comment]
I filed #274 to consider an alternative approach that mitigates the triple pace situation.

**Pull request merged**
